# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024  anaconda-gentoo contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Step 6 — Generate /etc/portage/make.conf from hardware detection."""
from __future__ import annotations

import multiprocessing
from pathlib import Path
from installer.state import InstallerState
from installer.steps.base import Step, StepError

# PCI class codes → USE flags
_CLASS_USE: dict[int, list[str]] = {
    0x0300: [],         # GPU — handled by VIDEO_CARDS below
    0x0403: ["alsa"],   # Audio
    0x0200: ["networkmanager"],  # Ethernet
    0x0280: ["wifi", "networkmanager"],  # Wireless
    0x0E00: [],         # Bluetooth (USB-based usually)
}

# PCI vendor+class → VIDEO_CARDS value
_GPU_VENDORS: dict[int, str] = {
    0x8086: "intel",
    0x1002: "amdgpu radeon",
    0x10DE: "nvidia",
    0x1AF4: "virgl",    # VirtIO GPU
    0x15AD: "vmware",
}

_MAKE_CONF_TEMPLATE = """\
# /etc/portage/make.conf
# Generated by anaconda-gentoo

CFLAGS="{cflags}"
CXXFLAGS="${{CFLAGS}}"
FCFLAGS="${{CFLAGS}}"
FFLAGS="${{CFLAGS}}"
MAKEOPTS="-j{jobs}"

USE="{use_flags}"

VIDEO_CARDS="{video_cards}"
INPUT_DEVICES="libinput"

ACCEPT_LICENSE="*"
GENTOO_MIRRORS="https://distfiles.gentoo.org"

GRUB_PLATFORMS="{grub_platform}"

FEATURES="parallel-fetch parallel-install"
"""


def _detect_use_flags(hw: dict) -> tuple[set[str], str, str]:
    """Return (use_flags, video_cards, grub_platform) from hardware dict."""
    use: set[str] = {"unicode", "udev"}
    video_cards = "fbdev vesa"
    grub_platform = "pc"

    pci_devs = hw.get("pci", [])
    for dev in pci_devs:
        cls = dev.get("cls", 0)
        base_cls = (cls >> 16) & 0xFF
        sub_cls = (cls >> 8) & 0xFF
        full_cls = (base_cls << 8) | sub_cls

        # Video cards
        if base_cls == 0x03:
            vendor = dev.get("vendor", 0)
            vc = _GPU_VENDORS.get(vendor, "")
            if vc:
                video_cards = vc

        # Other class-based USE flags
        for cls_key, flags in _CLASS_USE.items():
            if full_cls == (cls_key >> 8):
                use.update(flags)

    # ACPI
    acpi = hw.get("acpi", {})
    if acpi.get("has_acpi"):
        use.add("acpi")

    # UEFI → grub platform
    # (will be overridden by uefi detection in partition step)
    return use, video_cards, grub_platform


class MakeConfStep(Step):
    name = "makeconf"
    description = "Generating make.conf"

    def __init__(self, march: str = "native", extra_use: list[str] | None = None) -> None:
        self._march = march
        self._extra_use = extra_use or []

    def execute(self, state: InstallerState) -> None:
        hw = state.get("hardware", {})
        partitions = state.get("partitions", {})
        jobs = multiprocessing.cpu_count()
        cflags = f"-O2 -pipe -march={self._march}"

        use_flags, video_cards, grub_platform = _detect_use_flags(hw)
        use_flags.update(self._extra_use)

        if partitions.get("uefi"):
            grub_platform = "efi-64"
            use_flags.add("efi")

        mp = Path(state.mountpoint)
        portage_dir = mp / "etc" / "portage"
        portage_dir.mkdir(parents=True, exist_ok=True)

        conf = _MAKE_CONF_TEMPLATE.format(
            cflags=cflags,
            jobs=jobs,
            use_flags=" ".join(sorted(use_flags)),
            video_cards=video_cards,
            grub_platform=grub_platform,
        )

        conf_path = portage_dir / "make.conf"
        conf_path.write_text(conf)
        print(f"  Wrote {conf_path}")
        print(f"  USE=\"{' '.join(sorted(use_flags))}\"")
        print(f"  VIDEO_CARDS=\"{video_cards}\"")

        state.set("make_conf", {
            "cflags": cflags,
            "use": sorted(use_flags),
            "video_cards": video_cards,
            "grub_platform": grub_platform,
            "jobs": jobs,
        })
