# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024  anaconda-gentoo contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Step 9 — GRUB2 bootloader installation."""
from __future__ import annotations

import subprocess
from pathlib import Path
from installer.state import InstallerState
from installer.steps.base import Step, StepError
from installer.chroot import chroot_context, chroot_run


_GRUB_CFG_HEADER = """\
# Generated by anaconda-gentoo
GRUB_DEFAULT=0
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="Gentoo"
GRUB_CMDLINE_LINUX_DEFAULT="quiet"
GRUB_CMDLINE_LINUX=""
"""


class FstabStep(Step):
    name = "fstab"
    description = "Generating /etc/fstab"

    def execute(self, state: InstallerState) -> None:
        parts = state.get("partitions", {})
        mp = Path(state.mountpoint)
        root_fs = state.get("root_fs", "ext4")
        uefi = parts.get("uefi", False)

        def uuid_of(dev: str) -> str:
            try:
                r = subprocess.run(
                    ["blkid", "-s", "UUID", "-o", "value", dev],
                    capture_output=True, text=True, check=True,
                )
                return r.stdout.strip()
            except subprocess.CalledProcessError:
                return dev

        lines = [
            "# /etc/fstab — generated by anaconda-gentoo",
            "# <device>  <mountpoint>  <fstype>  <options>  <dump>  <pass>",
        ]

        root_uuid = uuid_of(parts["root"])
        lines.append(f"UUID={root_uuid}  /  {root_fs}  defaults,noatime  0 1")

        boot_uuid = uuid_of(parts["boot"])
        if uefi:
            lines.append(f"UUID={boot_uuid}  /boot/efi  vfat  defaults  0 2")
        else:
            lines.append(f"UUID={boot_uuid}  /boot  ext2  defaults  0 2")

        if parts.get("swap"):
            swap_uuid = uuid_of(parts["swap"])
            lines.append(f"UUID={swap_uuid}  none  swap  sw  0 0")

        lines.append("tmpfs  /tmp  tmpfs  nosuid,nodev  0 0")

        fstab = mp / "etc" / "fstab"
        fstab.write_text("\n".join(lines) + "\n")
        print(f"  Written {fstab}")


class BootloaderStep(Step):
    name = "bootloader"
    description = "Installing GRUB2 bootloader"

    def execute(self, state: InstallerState) -> None:
        parts = state.get("partitions", {})
        mp = Path(state.mountpoint)
        disk = state.get("disk", "")
        uefi = parts.get("uefi", False)
        make_conf = state.get("make_conf", {})
        grub_platform = make_conf.get("grub_platform", "pc")

        if not disk:
            raise StepError("Disk not set in state")

        # Write grub default config
        grub_etc = mp / "etc" / "default"
        grub_etc.mkdir(parents=True, exist_ok=True)
        (grub_etc / "grub").write_text(_GRUB_CFG_HEADER)

        with chroot_context(mp):
            # Install GRUB package if not present
            grub_bin = mp / "usr" / "sbin" / "grub-install"
            if not grub_bin.exists():
                print("  Installing grub via emerge...")
                chroot_run(mp, [
                    "emerge", "--quiet", f"--useflag=grub_platforms_{grub_platform}",
                    "sys-boot/grub",
                ])

            if uefi:
                print(f"  Installing GRUB (UEFI) to {disk}...")
                chroot_run(mp, [
                    "grub-install",
                    "--target=x86_64-efi",
                    "--efi-directory=/boot/efi",
                    "--removable",
                ])
            else:
                print(f"  Installing GRUB (BIOS) to {disk}...")
                chroot_run(mp, ["grub-install", disk])

            print("  Generating GRUB config...")
            chroot_run(mp, ["grub-mkconfig", "-o", "/boot/grub/grub.cfg"])

        print("  GRUB installed OK")
