# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024  anaconda-gentoo contributors
"""Tests for kconfig_builder.generator — .config file generation."""
import io
from pathlib import Path

import pytest

from kconfig_builder.generator import ConfigGenerator


def _generate(gen: ConfigGenerator) -> str:
    buf = io.StringIO()
    gen.write(buf)
    return buf.getvalue()


class TestConfigGenerator:

    def test_essential_symbols_present(self):
        gen = ConfigGenerator(detected_acpi=False)
        out = _generate(gen)
        assert "CONFIG_64BIT=y" in out
        assert "CONFIG_PRINTK=y" in out
        assert "CONFIG_MMU=y" in out
        assert "CONFIG_BINFMT_ELF=y" in out

    def test_acpi_included_when_detected(self):
        gen = ConfigGenerator(detected_acpi=True)
        out = _generate(gen)
        assert "CONFIG_ACPI=y" in out

    def test_acpi_absent_when_not_detected(self):
        gen = ConfigGenerator(detected_acpi=False)
        out = _generate(gen)
        assert "CONFIG_ACPI=y" not in out

    def test_add_module(self):
        gen = ConfigGenerator(detected_acpi=False)
        gen.add("IGB", "m", "hardware")
        out = _generate(gen)
        assert "CONFIG_IGB=m" in out

    def test_add_builtin(self):
        gen = ConfigGenerator(detected_acpi=False)
        gen.add("IGB", "y", "hardware")
        out = _generate(gen)
        assert "CONFIG_IGB=y" in out

    def test_no_downgrade_y_to_m(self):
        gen = ConfigGenerator(detected_acpi=False)
        gen.add("EXT4_FS", "y", "boot-critical")
        gen.add("EXT4_FS", "m", "hardware")  # should be ignored
        out = _generate(gen)
        assert "CONFIG_EXT4_FS=y" in out
        assert "CONFIG_EXT4_FS=m" not in out

    def test_add_many(self):
        gen = ConfigGenerator(detected_acpi=False)
        gen.add_many({"IGB", "E1000E", "IXGBE"}, value="m", section="hardware")
        out = _generate(gen)
        assert "CONFIG_IGB=m" in out
        assert "CONFIG_E1000E=m" in out
        assert "CONFIG_IXGBE=m" in out

    def test_disabled_symbol_format(self):
        gen = ConfigGenerator(detected_acpi=False)
        gen.add("SOME_UNUSED", "n", "")
        out = _generate(gen)
        assert "# CONFIG_SOME_UNUSED is not set" in out

    def test_save_to_file(self, tmp_path):
        gen = ConfigGenerator(detected_acpi=False)
        gen.add("IGB", "m", "hardware")
        out_file = tmp_path / ".config"
        gen.save(out_file)
        content = out_file.read_text()
        assert "CONFIG_IGB=m" in content
        assert "CONFIG_64BIT=y" in content

    def test_meta_in_header(self):
        gen = ConfigGenerator(detected_acpi=False)
        out = _generate(gen)
        assert "Generated by anaconda-gentoo" in out or "kconfig-builder" in out

    def test_total_symbols(self):
        gen = ConfigGenerator(detected_acpi=False)
        initial = gen.total_symbols
        gen.add("IGB", "m", "hardware")
        assert gen.total_symbols == initial + 1

    def test_duplicate_add_no_double_entry(self):
        gen = ConfigGenerator(detected_acpi=False)
        gen.add("IGB", "m", "hardware")
        gen.add("IGB", "m", "hardware")
        out = _generate(gen)
        assert out.count("CONFIG_IGB=") == 1
