# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024  anaconda-gentoo contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Generate a full Linux kernel .config from resolved CONFIG symbols."""
from __future__ import annotations

import datetime
from pathlib import Path
from typing import TextIO

# Always-on essentials required for a bootable kernel
_ESSENTIAL: dict[str, str] = {
    # Architecture
    "64BIT": "y",
    # Core
    "PRINTK": "y",
    "BUG": "y",
    "ELF_CORE": "y",
    "MULTIUSER": "y",
    "SYSFS": "y",
    "PROC_FS": "y",
    "TMPFS": "y",
    "DEVTMPFS": "y",
    "DEVTMPFS_MOUNT": "y",
    # Memory
    "MMU": "y",
    "SLUB": "y",
    # Executable formats
    "BINFMT_ELF": "y",
    "BINFMT_SCRIPT": "y",
    # Filesystems
    "EXT4_FS": "y",
    "EXT4_USE_FOR_EXT2": "y",
    "VFAT_FS": "y",
    "FAT_FS": "y",
    "ISO9660_FS": "y",
    "TMPFS_POSIX_ACL": "y",
    # Networking base
    "NET": "y",
    "INET": "y",
    "IPV6": "m",
    # PCI infrastructure
    "PCI": "y",
    "PCIEPORTBUS": "y",
    "PCI_MSI": "y",
    # USB infrastructure
    "USB_SUPPORT": "y",
    "USB": "m",
    "USB_ANNOUNCE_NEW_DEVICES": "y",
    # Block layer
    "BLOCK": "y",
    "BLK_DEV_BSG": "y",
    # IRQ and timer
    "GENERIC_IRQ_CHIP": "y",
    "GENERIC_IRQ_PROBE": "y",
    "GENERIC_IRQ_SHOW": "y",
    # ACPI (if present, will be overridden per detection)
    "ACPI": "y",
    # Clock
    "CLKEVT_HPET": "y",
    # Power management
    "PM": "y",
    "PM_SLEEP": "y",
    "SUSPEND": "y",
    # Init
    "SHMEM": "y",
    "EMBEDDED": "n",
    # Crypto base (often a dependency)
    "CRYPTO": "y",
    "CRYPTO_ALGAPI": "y",
    "CRYPTO_HASH": "y",
    # Misc
    "MODULES": "y",
    "MODULE_UNLOAD": "y",
    "KALLSYMS": "y",
    "PRINTK_TIME": "y",
    "EARLY_PRINTK": "y",
}

# These symbols should be explicitly set to 'n' (not just omitted)
_DISABLED: list[str] = [
    "LOCALVERSION_AUTO",
    "WERROR",
]


class ConfigGenerator:
    def __init__(self, detected_acpi: bool = False) -> None:
        # symbol → (value, section)
        self._entries: dict[str, tuple[str, str]] = {}
        base = dict(_ESSENTIAL)
        if not detected_acpi:
            base.pop("ACPI", None)
            base.pop("CLKEVT_HPET", None)
        for sym, val in base.items():
            self._entries[sym] = (val, "essential")

    def add(self, symbol: str, value: str = "m", section: str = "") -> None:
        # Don't downgrade essential 'y' to 'm'
        if symbol in self._entries and self._entries[symbol][0] == "y":
            return
        self._entries[symbol] = (value, section)

    def add_many(
        self, symbols: set[str], value: str = "m", section: str = ""
    ) -> None:
        for sym in sorted(symbols):
            self.add(sym, value, section)

    def write(self, out: TextIO, meta: dict | None = None) -> None:
        ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        out.write(f"# Linux kernel configuration\n")
        out.write(f"# Generated by kconfig-builder on {ts}\n")
        if meta:
            for k, v in meta.items():
                out.write(f"# {k}: {v}\n")
        out.write("\n")

        # Group by section
        sections: dict[str, list[tuple[str, str]]] = {}
        for sym, (val, sec) in self._entries.items():
            sections.setdefault(sec, []).append((sym, val))

        section_order = ["essential", "hardware", "dependency", "acpi", ""]
        written_sections: set[str] = set()

        for sec in section_order + sorted(s for s in sections if s not in section_order):
            if sec not in sections or sec in written_sections:
                continue
            written_sections.add(sec)
            entries = sorted(sections[sec], key=lambda x: x[0])
            if sec:
                out.write(f"# --- {sec.capitalize()} ---\n")
            for sym, val in entries:
                if val == "n":
                    out.write(f"# CONFIG_{sym} is not set\n")
                else:
                    out.write(f"CONFIG_{sym}={val}\n")
            out.write("\n")

        # Write explicit disabled symbols
        out.write("# --- Disabled ---\n")
        for sym in _DISABLED:
            if sym not in self._entries:
                out.write(f"# CONFIG_{sym} is not set\n")
        out.write("\n")

    def save(self, path: Path, meta: dict | None = None) -> None:
        with open(path, "w") as f:
            self.write(f, meta)

    @property
    def total_symbols(self) -> int:
        return len(self._entries)
